### ISSUE TITLE
remove method failing

### ISSUE THREAD

**Issue by brianleroux** [xuijs/xui#1] opened 2010-09-01 21:20 UTC
when selector undefined

x$('#nothere').remove(); // throws exception

**Comment by filmaj** [comment] 2011-01-09 03:17
Created a test for this one and can't reproduce on Chrome 8 or Safari 5.0.3: fc3f54e0fd33ff0e7e598cf80fbb89937126b705

Gonna close this one.

**Closed as completed by filmaj** 2011-01-09 03:17 UTC
